const V='study-pwa-v12-7-4-continue-code';
const CORE=['./','./index.html','./manifest.webmanifest?v=12.4','./assets/css/app.css?v=12.7.4','./assets/js/config.js?v=12.7','./assets/js/cloud-core.js?v=12.5','./assets/js/app.js?v=12.7.4','./assets/study-collage.jpg','./data/catalog.json','./reader.html','./offline.html'];
const UI_ICONS=['./assets/ui-icons/sf-black-filled/admin.png','./assets/ui-icons/sf-black-filled/archive.png','./assets/ui-icons/sf-black-filled/calendar.png','./assets/ui-icons/sf-black-filled/chevron-left.png','./assets/ui-icons/sf-black-filled/chevron-right.png','./assets/ui-icons/sf-black-filled/close.png','./assets/ui-icons/sf-black-filled/cloud.png','./assets/ui-icons/sf-black-filled/courses.png','./assets/ui-icons/sf-black-filled/device.png','./assets/ui-icons/sf-black-filled/document.png','./assets/ui-icons/sf-black-filled/download.png','./assets/ui-icons/sf-black-filled/grid.png','./assets/ui-icons/sf-black-filled/home.png','./assets/ui-icons/sf-black-filled/list.png','./assets/ui-icons/sf-black-filled/maps.png','./assets/ui-icons/sf-black-filled/more.png','./assets/ui-icons/sf-black-filled/plus.png','./assets/ui-icons/sf-black-filled/progress.png','./assets/ui-icons/sf-black-filled/search.png','./assets/ui-icons/sf-black-filled/settings.png','./assets/ui-icons/sf-black-filled/star.png','./assets/ui-icons/sf-black-filled/success.png','./assets/ui-icons/sf-black-filled/sync.png','./assets/ui-icons/sf-black-filled/trash.png','./assets/ui-icons/sf-black-filled/upload.png','./assets/ui-icons/sf-black-filled/user.png','./assets/ui-icons/sf-black-filled/warning.png'];
const BRAND_ASSETS=['./assets/brand/logo/logo-horizontal.png','./assets/brand/logo/marca-simplificada.png','./assets/brand/app-icons/apple-touch-icon.png','./assets/brand/app-icons/icon-192.png','./assets/brand/app-icons/icon-512.png','./assets/brand/app-icons/icon-maskable-192.png','./assets/brand/app-icons/icon-maskable-512.png','./assets/brand/favicon/favicon.ico','./assets/brand/favicon/favicon-16x16.png','./assets/brand/favicon/favicon-32x32.png','./assets/brand/favicon/favicon-48x48.png','./assets/brand/favicon/favicon-96x96.png'];
const sameOrigin=request=>new URL(request.url).origin===self.location.origin;
const absolute=path=>new URL(path,self.registration.scope).href;
async function cacheOptional(cache,path){try{const req=new Request(absolute(path),{cache:'reload'}),r=await fetch(req);if(r.ok)await cache.put(req,r)}catch{}}
async function cacheCatalogResources(cache){try{const req=new Request(absolute('./data/catalog.json'),{cache:'reload'}),r=await fetch(req);if(!r.ok)return;const data=await r.clone().json();await cache.put(req,r);const paths=[...(data.maps||[]).flatMap(m=>[m.href,m.cover]),...(data.courses||[]).map(c=>c.edital)].filter(Boolean);await Promise.allSettled(paths.map(p=>cacheOptional(cache,'./'+String(p).replace(/^\.\//,''))))}catch{}}
async function networkFirst(request,fallback){try{const r=await fetch(request);if(r&&r.ok){const cache=await caches.open(V);await cache.put(request,r.clone())}return r}catch{const hit=await caches.match(request,{ignoreSearch:true});if(hit)return hit;if(fallback){const fb=await caches.match(absolute(fallback),{ignoreSearch:true});if(fb)return fb}return new Response('Offline',{status:503,statusText:'Offline'})}}
async function cacheFirst(request){const hit=await caches.match(request);if(hit)return hit;try{const r=await fetch(request);if(r&&r.ok){const cache=await caches.open(V);await cache.put(request,r.clone())}return r}catch{return new Response('Offline',{status:503,statusText:'Offline'})}}
self.addEventListener('install',e=>e.waitUntil((async()=>{const cache=await caches.open(V);await cache.addAll([...CORE,...UI_ICONS,...BRAND_ASSETS]);await cacheCatalogResources(cache);await self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('study-pwa-')&&k!==V).map(k=>caches.delete(k)));await self.clients.claim()})()));
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET'||!sameOrigin(r))return;const u=new URL(r.url);if(r.mode==='navigate'){const fallback=u.pathname.endsWith('/reader.html')?'./reader.html':'./index.html';e.respondWith(networkFirst(r,fallback));return}if(/\/cursos\/.*\/(?:mapas\/.*\.html|documentos\/.*\.pdf)$/i.test(u.pathname)||/\/data\/catalog\.json$/i.test(u.pathname)){e.respondWith(networkFirst(r));return}e.respondWith(cacheFirst(r))});
